version: '2'
services:
  kibana:
    build: ./docker/kb-docker/. 
    expose:
      - "5601"
    ports:
     - "5601:5601"
    environment:
      SERVER_HOST: "0.0.0.0"
  elasticsearch:
    build: ./docker/es-docker/.
    ports:
     - "9200:9200"
    expose:
      - "9200"
    environment:
      SERVER_NAME: "elasticsearch"
    volumes:
      - tlre-es-data:/usr/share/elasticsearch/data
  splainer:
    platform: linux/amd64
    image: o19s/splainer
    ports:
     - "9000:9000"
    expose:
      - "9000"
  redis:
    platform: linux/amd64
    image: 'bitnami/redis:latest'
    ports:
     - "6399:6379"
    expose:
      - "6399"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_APPENDONLY=yes
    volumes:
      - tlre-redis-data:/bitnami/redis/data

volumes:
  tlre-es-data:
    driver: local
  tlre-redis-data:
    driver: local
